registry: http://registry.npmjs.org


sync:
  batch-size: 200
  batch-delay: 1000
  interval: 1 # sync interval in seconds
  concurrency: 10
  max-queue-size: 1000
  
elasticsearch:
  host: "http://localhost:9200"
  index: 'npm'
  log: "trace"


log:
  level: debug
  