sync:
  interval: 1000 
  concurrency: 10
  max-queue-size: 2
  
elasticsearch:
  host: "http://localhost:9200"
  index: "npm"
  log: "error"


  registry: "http://registry.npmjs.org"
couchdb: "https://skimdb.npmjs.com/registry"

log:
  level: "info"
  