sync:
  batch-size: 100
  interval: 1000 # sync interval in seconds
  registry: http://registry.npmjs.org
  concurrency: 20
  max-queue-size: 1000
  
elasticsearch:
  host: "localhost:9301"
  log: "trace"


log:
  level: debug
  